export const SEED_RESTAURANTS = [
  {
    id: 1,
    name: "Riverbar & Kitchen",
    category: "Modern Australian",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4679,
      longitude: 153.0303,
    },
    price_range: {min: 20, max:70},
    rating: 4.6,
    reviewCount: 428,
    availableToday: true,
    trending: true,
    short_description:
      "Riverside dining with modern Australian plates, cocktails, and city views.",
    features: [
      "River View",
      "Cocktail Bar",
      "Outdoor Seating",
      "Live Music",
    ],
    popular_dishes: [
      "Ribeye Steak",
      "Truffle Fries",
      "Grilled Barramundi",
    ],
    tags: ["Trending", "Waterfront", "Nightlife"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 2,
    name: "South Bankside Grill",
    category: "Steakhouse",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4703,
      longitude: 153.0224,
    },
    price_range: {min: 120, max: 180},
    rating: 4.8,
    reviewCount: 612,
    availableToday: true,
    trending: true,
    short_description:
      "Premium Australian steaks and wine overlooking Brisbane's South Bank.",
    features: [
      "Fine Dining",
      "Wine List",
      "Private Dining",
      "City Views",
    ],
    popular_dishes: [
      "Wagyu Ribeye",
      "Surf and Turf",
      "Truffle Fries",
    ],
    tags: ["Steak", "Fine Dining", "Date Night"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 3,
    name: "Burger House",
    category: "American",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4705,
      longitude: 153.031,
    },
    price_range: {min: 20, max: 40},
    rating: 4.5,
    reviewCount: 351,
    availableToday: true,
    trending: true,
    short_description:
      "Juicy smashed burgers, crispy fries, and thick shakes in a casual setting.",
    features: [
      "Fast Service",
      "Takeaway",
      "Late Night",
      "Casual Dining",
    ],
    popular_dishes: [
      "Double Cheeseburger",
      "Loaded Fries",
      "Chocolate Shake",
    ],
    tags: ["Burgers", "Popular", "Comfort Food"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 4,
    name: "The Dumpling House",
    category: "Chinese",
    image:
      "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.443,
      longitude: 153.052,
    },
    price_range: {min: 20, max: 40},
    rating: 4.7,
    reviewCount: 286,
    availableToday: true,
    trending: false,
    short_description:
      "Handmade dumplings, noodles, and traditional Chinese favourites for sharing.",
    features: [
      "Yum Cha",
      "Takeaway",
      "Family Style",
      "Large Groups",
    ],
    popular_dishes: [
      "Xiao Long Bao",
      "Pork Dumplings",
      "Kung Pao Chicken",
    ],
    tags: ["Dumplings", "Chinese", "Yum Cha"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },

  {
    id: 5,
    name: "Ocean Catch",
    category: "Seafood",
    image:
      "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.46,
      longitude: 153.0458,
    },
    price_range: {min: 40, max: 120},
    rating: 4.5,
    reviewCount: 219,
    availableToday: true,
    trending: false,
    short_description:
      "Fresh seafood, grilled fish, and generous platters inspired by the coast.",
    features: [
      "Fresh Daily",
      "Outdoor Seating",
      "Waterfront View",
      "Family Friendly",
    ],
    popular_dishes: [
      "Grilled Barramundi",
      "Seafood Platter",
      "Fish and Chips",
    ],
    tags: ["Seafood", "Fresh", "Waterfront"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 6,
    name: "The Curry House",
    category: "Indian",
    image:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4847,
      longitude: 153.0323,
    },
    price_range: {min: 20, max: 40},
    rating: 4.4,
    reviewCount: 174,
    availableToday: true,
    trending: false,
    short_description:
      "Comforting Indian curries, tandoori favourites, and freshly baked naan.",
    features: [
      "Halal",
      "Vegetarian Options",
      "Takeaway",
      "Family Dining",
    ],
    popular_dishes: [
      "Butter Chicken",
      "Lamb Rogan Josh",
      "Garlic Naan",
    ],
    tags: ["Curry", "Indian", "Spicy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 7,
    name: "Taco Fiesta",
    category: "Mexican",
    image:
      "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4689,
      longitude: 153.0582,
    },
    price_range: {min: 20, max: 40},
    rating: 4.6,
    reviewCount: 307,
    availableToday: true,
    trending: true,
    short_description:
      "Street-style Mexican food, fresh tacos, margaritas, and a lively atmosphere.",
    features: [
      "Margarita Bar",
      "Casual Dining",
      "Takeaway",
      "Live Music",
    ],
    popular_dishes: [
      "Street Tacos",
      "Loaded Nachos",
      "Chicken Quesadilla",
    ],
    tags: ["Tacos", "Mexican", "Spicy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 8,
    name: "Coffee & Co",
    category: "Cafe",
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4616,
      longitude: 153.0571,
    },
    price_range: {min: 20, max: 40},
    rating: 4.8,
    reviewCount: 493,
    availableToday: true,
    trending: true,
    short_description:
      "Neighbourhood coffee, all-day brunch, and relaxed mornings with friends.",
    features: [
      "Coffee Bar",
      "Breakfast All Day",
      "Outdoor Seating",
      "Pet Friendly",
    ],
    popular_dishes: [
      "Avocado Toast",
      "Eggs Benedict",
      "Flat White",
    ],
    tags: ["Brunch", "Coffee", "Breakfast"],
    time_opening: [
      "06:30",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
    ],
  },

  {
    id: 9,
    name: "The Wok Station",
    category: "Chinese",
    image:
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4689,
      longitude: 153.0063,
    },
    price_range: {min: 20, max: 60},
    rating: 4.3,
    reviewCount: 142,
    availableToday: true,
    trending: false,
    short_description:
      "Quick and flavourful Chinese dishes served straight from the wok.",
    features: [
      "Quick Service",
      "Takeaway",
      "Family Style",
      "Late Night",
    ],
    popular_dishes: [
      "Beef Chow Mein",
      "Kung Pao Chicken",
      "Fried Rice",
    ],
    tags: ["Chinese", "Wok", "Casual"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 10,
    name: "The Falafel Stop",
    category: "Middle Eastern",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4631,
      longitude: 153.0131,
    },
    price_range: {min: 20, max: 40},
    rating: 4.5,
    reviewCount: 198,
    availableToday: true,
    trending: false,
    short_description:
      "Fresh Middle Eastern favourites with falafel, hummus, wraps, and grilled meats.",
    features: [
      "Vegetarian Options",
      "Halal",
      "Takeaway",
      "Quick Service",
    ],
    popular_dishes: [
      "Falafel Wrap",
      "Hummus Plate",
      "Chicken Shawarma",
    ],
    tags: ["Middle Eastern", "Falafel", "Vegetarian"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },

  {
    id: 11,
    name: "Sakura Sushi",
    category: "Japanese",
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4862,
      longitude: 153.056,
    },
    price_range: {min: 40, max: 120},
    rating: 4.8,
    reviewCount: 536,
    availableToday: true,
    trending: true,
    short_description:
      "Elegant Japanese dining featuring sushi, sashimi, ramen, and sake.",
    features: [
      "Omakase",
      "Sake Bar",
      "Sushi Bar",
      "Late Night",
    ],
    popular_dishes: [
      "Salmon Nigiri",
      "Tonkotsu Ramen",
      "Chicken Katsu",
    ],
    tags: ["Sushi", "Ramen", "Japanese"],
    time_opening: [
      "11:30",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 12,
    name: "The Diner Co",
    category: "American",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4681,
      longitude: 153.0101,
    },
    price_range: {min: 8, max: 30},
    rating: 4.2,
    reviewCount: 126,
    availableToday: true,
    trending: false,
    short_description:
      "Classic American comfort food with burgers, ribs, fries, and milkshakes.",
    features: [
      "Fast Service",
      "Takeaway",
      "Casual Dining",
      "Late Night",
    ],
    popular_dishes: [
      "Double Cheeseburger",
      "BBQ Ribs",
      "Loaded Fries",
    ],
    tags: ["Burgers", "Comfort Food", "BBQ"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 13,
    name: "Little Lisbon",
    category: "Portuguese",
    image:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4764,
      longitude: 153.0324,
    },
    price_range: {min: 20, max: 60},
    rating: 4.6,
    reviewCount: 187,
    availableToday: true,
    trending: false,
    short_description:
      "Warm Portuguese dining with grilled meats, seafood, and a thoughtful wine list.",
    features: [
      "Wine List",
      "Casual Dining",
      "Outdoor Seating",
      "Family Friendly",
    ],
    popular_dishes: [
      "Piri Piri Chicken",
      "Bacalhau",
      "Pastel de Nata",
    ],
    tags: ["Portuguese", "Grilled", "Wine"],
    time_opening: [
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 14,
    name: "Seoul Kitchen",
    category: "Korean",
    image:
      "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4669,
      longitude: 153.026,
    },
    price_range: {min: 20, max: 40},
    rating: 4.7,
    reviewCount: 274,
    availableToday: true,
    trending: true,
    short_description:
      "Korean BBQ, comforting rice bowls, and bold flavours in a lively setting.",
    features: [
      "BBQ Grill",
      "Late Night",
      "Group Dining",
      "Casual Dining",
    ],
    popular_dishes: [
      "Korean BBQ Beef",
      "Bibimbap",
      "Kimchi Fried Rice",
    ],
    tags: ["Korean BBQ", "Korean", "Spicy"],
    time_opening: [
      "11:30",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 15,
    name: "The Bagel Shop",
    category: "Cafe",
    image:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4425,
      longitude: 153.0586,
    },
    price_range: {min: 20, max: 40},
    rating: 4.4,
    reviewCount: 215,
    availableToday: true,
    trending: false,
    short_description:
      "Freshly baked bagels, specialty coffee, and easy-going brunch favourites.",
    features: [
      "Coffee Bar",
      "Breakfast",
      "Takeaway",
      "Outdoor Seating",
    ],
    popular_dishes: [
      "Smoked Salmon Bagel",
      "Eggs Benedict",
      "Flat White",
    ],
    tags: ["Brunch", "Coffee", "Breakfast"],
    time_opening: [
      "06:30",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
    ],
  },

  {
    id: 16,
    name: "Casa Amigos",
    category: "Mexican",
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4637,
      longitude: 153.0321,
    },
    price_range: {min: 20, max: 60},
    rating: 4.5,
    reviewCount: 243,
    availableToday: true,
    trending: false,
    short_description:
      "Colourful Mexican dining with tacos, fresh guacamole, and margaritas.",
    features: [
      "Margarita Bar",
      "Casual Dining",
      "Takeaway",
      "Live Music",
    ],
    popular_dishes: [
      "Street Tacos",
      "Loaded Nachos",
      "Chicken Fajitas",
    ],
    tags: ["Tacos", "Mexican", "Spicy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 17,
    name: "Aussie Grill",
    category: "Australian",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4928,
      longitude: 153.0176,
    },
    price_range: {min: 20, max: 60},
    rating: 4.3,
    reviewCount: 189,
    availableToday: true,
    trending: false,
    short_description:
      "Relaxed Australian dining with classic pub favourites and generous portions.",
    features: [
      "Outdoor Seating",
      "Family Friendly",
      "Casual Dining",
      "Large Groups",
    ],
    popular_dishes: [
      "Chicken Parma",
      "Lamb Roast",
      "Fish and Chips",
    ],
    tags: ["Aussie", "Pub Food", "Comfort Food"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 18,
    name: "Spice Route",
    category: "Thai",
    image:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4785,
      longitude: 153.0273,
    },
    price_range: {min: 20, max: 40},
    rating: 4.5,
    reviewCount: 231,
    availableToday: true,
    trending: false,
    short_description:
      "A vibrant Thai kitchen serving fragrant curries, noodles, and fresh herbs.",
    features: [
      "Vegetarian Options",
      "Takeaway",
      "Spicy Menu",
      "Casual Dining",
    ],
    popular_dishes: [
      "Pad Thai",
      "Green Curry",
      "Mango Sticky Rice",
    ],
    tags: ["Thai", "Curry", "Spicy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 19,
    name: "The Greek Isles",
    category: "Mediterranean",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4786,
      longitude: 153.046,
    },
    price_range: {min: 20, max: 60},
    rating: 4.6,
    reviewCount: 205,
    availableToday: true,
    trending: false,
    short_description:
      "Fresh Mediterranean plates with grilled meats, salads, and traditional Greek flavours.",
    features: [
      "Vegetarian Options",
      "Outdoor Seating",
      "Halal",
      "Family Friendly",
    ],
    popular_dishes: [
      "Lamb Souvlaki",
      "Greek Salad",
      "Baklava",
    ],
    tags: ["Mediterranean", "Greek", "Healthy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 20,
    name: "Mediterraneo",
    category: "Mediterranean",
    image:
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4889,
      longitude: 153.0488,
    },
    price_range: {min: 20, max: 40},
    rating: 4.4,
    reviewCount: 158,
    availableToday: true,
    trending: false,
    short_description:
      "Relaxed Mediterranean dining focused on fresh ingredients and shareable plates.",
    features: [
      "Vegetarian Options",
      "Outdoor Seating",
      "Wine List",
      "Family Friendly",
    ],
    popular_dishes: [
      "Lamb Souvlaki",
      "Greek Salad",
      "Grilled Halloumi",
    ],
    tags: ["Mediterranean", "Greek", "Healthy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },

  {
    id: 21,
    name: "Sushi Zen",
    category: "Japanese",
    image:
      "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4727,
      longitude: 153.0196,
    },
    price_range: {min: 20, max: 60},
    rating: 4.6,
    reviewCount: 342,
    availableToday: true,
    trending: true,
    short_description:
      "Minimalist Japanese dining with fresh sushi, ramen, and delicate small plates.",
    features: [
      "Sushi Bar",
      "Omakase",
      "Takeaway",
      "Late Night",
    ],
    popular_dishes: [
      "Salmon Nigiri",
      "Tonkotsu Ramen",
      "Chicken Katsu",
    ],
    tags: ["Sushi", "Ramen", "Japanese"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 22,
    name: "Blue Elephant",
    category: "Thai",
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4921,
      longitude: 153.0433,
    },
    price_range: {min: 20, max: 60},
    rating: 4.3,
    reviewCount: 176,
    availableToday: true,
    trending: false,
    short_description:
      "Bold Thai flavours, aromatic curries, and comforting noodle dishes.",
    features: [
      "Vegetarian Options",
      "Takeaway",
      "Spicy Menu",
      "Family Dining",
    ],
    popular_dishes: [
      "Pad Thai",
      "Green Curry",
      "Tom Yum Soup",
    ],
    tags: ["Thai", "Curry", "Spicy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 23,
    name: "The Poke Bowl",
    category: "Hawaiian",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4676,
      longitude: 153.0411,
    },
    price_range: {min: 20, max: 60},
    rating: 4.7,
    reviewCount: 288,
    availableToday: true,
    trending: true,
    short_description:
      "Fresh poke bowls packed with seafood, vegetables, rice, and tropical flavours.",
    features: [
      "Healthy Options",
      "Takeaway",
      "Casual Dining",
      "Gluten Free Options",
    ],
    popular_dishes: [
      "Salmon Poke Bowl",
      "Tuna Poke Bowl",
      "Coconut Rice",
    ],
    tags: ["Poke", "Healthy", "Hawaiian"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },

  {
    id: 24,
    name: "Brunch & Co",
    category: "Cafe",
    image:
      "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4464,
      longitude: 153.0398,
    },
    price_range: {min: 20, max: 40},
    rating: 4.7,
    reviewCount: 412,
    availableToday: true,
    trending: true,
    short_description:
      "Bright neighbourhood brunch spot serving coffee, eggs, and fresh seasonal plates.",
    features: [
      "Coffee Bar",
      "Breakfast All Day",
      "Outdoor Seating",
      "Pet Friendly",
    ],
    popular_dishes: [
      "Smashed Avocado",
      "Eggs Benedict",
      "Pancakes",
    ],
    tags: ["Brunch", "Coffee", "Breakfast"],
    time_opening: [
      "06:30",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
    ],
  },

  {
    id: 25,
    name: "The Fish Market",
    category: "Seafood",
    image:
      "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4938,
      longitude: 153.0024,
    },
    price_range: {min: 20, max: 40},
    rating: 4.2,
    reviewCount: 137,
    availableToday: true,
    trending: false,
    short_description:
      "Casual seafood dining with fresh fish, chips, oysters, and daily specials.",
    features: [
      "Fresh Daily",
      "Takeaway",
      "Outdoor Seating",
      "Family Friendly",
    ],
    popular_dishes: [
      "Grilled Barramundi",
      "Seafood Platter",
      "Fish and Chips",
    ],
    tags: ["Seafood", "Fresh", "Casual"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },

  {
    id: 26,
    name: "Chili's Cantina",
    category: "Mexican",
    image:
      "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4531,
      longitude: 153.0609,
    },
    price_range: {min: 20, max: 40},
    rating: 4.4,
    reviewCount: 263,
    availableToday: true,
    trending: false,
    short_description:
      "Casual Mexican dining with tacos, burritos, margaritas, and plenty of spice.",
    features: [
      "Margarita Bar",
      "Casual Dining",
      "Takeaway",
      "Live Music",
    ],
    popular_dishes: [
      "Beef Tacos",
      "Loaded Nachos",
      "Chicken Burrito",
    ],
    tags: ["Tacos", "Mexican", "Spicy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 27,
    name: "Vegan Vibes",
    category: "Vegan",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.498,
      longitude: 153.0283,
    },
    price_range: {min: 20, max: 60},
    rating: 4.8,
    reviewCount: 317,
    availableToday: true,
    trending: true,
    short_description:
      "Creative plant-based food made with fresh produce and bold natural flavours.",
    features: [
      "Plant Based",
      "Gluten Free Options",
      "Healthy Options",
      "Casual Dining",
    ],
    popular_dishes: [
      "Buddha Bowl",
      "Vegan Burger",
      "Acai Bowl",
    ],
    tags: ["Vegan", "Healthy", "Plant Based"],
    time_opening: [
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
    ],
  },

  {
    id: 28,
    name: "The Steakhouse",
    category: "Steakhouse",
    image:
      "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4574,
      longitude: 153.0063,
    },
    price_range: {min: 40, max: 120},
    rating: 4.7,
    reviewCount: 493,
    availableToday: true,
    trending: true,
    short_description:
      "Classic steakhouse dining focused on premium cuts, wine, and elegant service.",
    features: [
      "Wine List",
      "Fine Dining",
      "Private Dining",
      "Date Night",
    ],
    popular_dishes: [
      "Wagyu Ribeye",
      "Surf and Turf",
      "Truffle Fries",
    ],
    tags: ["Steak", "Fine Dining", "Wagyu"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 29,
    name: "Smash & Co",
    category: "American",
    image:
      "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4626,
      longitude: 153.0489,
    },
    price_range: {min: 20, max: 40},
    rating: 4.6,
    reviewCount: 326,
    availableToday: true,
    trending: true,
    short_description:
      "Crispy-edged smash burgers, loaded fries, and classic American sides.",
    features: [
      "Fast Service",
      "Takeaway",
      "Late Night",
      "Casual Dining",
    ],
    popular_dishes: [
      "Double Smash Burger",
      "Loaded Fries",
      "Chicken Burger",
    ],
    tags: ["Burgers", "Comfort Food", "Popular"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 30,
    name: "Nonna's Table",
    category: "Italian",
    image:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4898,
      longitude: 153.0105,
    },
    price_range: {min: 20, max: 60},
    rating: 4.8,
    reviewCount: 376,
    availableToday: true,
    trending: true,
    short_description:
      "Homestyle Italian cooking with handmade pasta, pizza, and family recipes.",
    features: [
      "Wine List",
      "Romantic",
      "Family Friendly",
      "Outdoor Seating",
    ],
    popular_dishes: [
      "Margherita Pizza",
      "Fettuccine Alfredo",
      "Tiramisu",
    ],
    tags: ["Pizza", "Pasta", "Italian"],
    time_opening: [
      "11:30",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 31,
    name: "Bangkok Nights",
    category: "Thai",
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.464,
      longitude: 153.0587,
    },
    price_range: {min: 20, max: 40},
    rating: 4.5,
    reviewCount: 248,
    availableToday: true,
    trending: true,
    short_description:
      "Lively Thai dining with fragrant curries, noodles, cocktails, and late-night bites.",
    features: [
      "Vegetarian Options",
      "Takeaway",
      "Spicy Menu",
      "Late Night",
    ],
    popular_dishes: [
      "Pad Thai",
      "Green Curry",
      "Mango Sticky Rice",
    ],
    tags: ["Thai", "Curry", "Nightlife"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
      "00:00",
    ],
  },

  {
    id: 32,
    name: "Le Petit Bistro",
    category: "French",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4873,
      longitude: 153.0439,
    },
    price_range: {min: 40, max: 120},
    rating: 4.7,
    reviewCount: 291,
    availableToday: true,
    trending: false,
    short_description:
      "Intimate French dining with classic dishes, wine, and a romantic atmosphere.",
    features: [
      "Wine List",
      "Romantic",
      "Fine Dining",
      "Date Night",
    ],
    popular_dishes: [
      "Coq au Vin",
      "French Onion Soup",
      "Crème Brûlée",
    ],
    tags: ["French", "Fine Dining", "Romantic"],
    time_opening: [
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 33,
    name: "The Ramen Bar",
    category: "Japanese",
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4915,
      longitude: 153.0535,
    },
    price_range: {min: 20, max: 40},
    rating: 4.8,
    reviewCount: 461,
    availableToday: true,
    trending: true,
    short_description:
      "Rich ramen broths, handmade noodles, and Japanese comfort food served late.",
    features: [
      "Ramen Bar",
      "Sake Bar",
      "Takeaway",
      "Late Night",
    ],
    popular_dishes: [
      "Tonkotsu Ramen",
      "Spicy Miso Ramen",
      "Gyoza",
    ],
    tags: ["Ramen", "Japanese", "Late Night"],
    time_opening: [
      "11:30",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
      "00:00",
    ],
  },

  {
    id: 34,
    name: "Pho Saigon",
    category: "Vietnamese",
    image:
      "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4741,
      longitude: 153.0422,
    },
    price_range: {min: 20, max: 40},
    rating: 4.7,
    reviewCount: 398,
    availableToday: true,
    trending: false,
    short_description:
      "Fragrant Vietnamese pho, fresh herbs, banh mi, and comforting noodle dishes.",
    features: [
      "Takeaway",
      "Casual Dining",
      "Vegetarian Options",
      "Quick Service",
    ],
    popular_dishes: [
      "Beef Pho",
      "Banh Mi",
      "Vietnamese Spring Rolls",
    ],
    tags: ["Pho", "Vietnamese", "Comfort Food"],
    time_opening: [
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },

  {
    id: 35,
    name: "Istanbul Grill",
    category: "Turkish",
    image:
      "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4473,
      longitude: 153.0414,
    },
    price_range: {min: 20, max: 60},
    rating: 4.5,
    reviewCount: 184,
    availableToday: true,
    trending: false,
    short_description:
      "Turkish grilled meats, fresh salads, and traditional dishes served generously.",
    features: [
      "Halal",
      "Takeaway",
      "Casual Dining",
      "Family Style",
    ],
    popular_dishes: [
      "Chicken Doner Kebab",
      "Lahmacun",
      "Mixed Grill",
    ],
    tags: ["Turkish", "Kebab", "Halal"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 36,
    name: "Mama Mia Pizzeria",
    category: "Italian",
    image:
      "https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4423,
      longitude: 153.0457,
    },
    price_range: {min: 20, max: 40},
    rating: 4.4,
    reviewCount: 224,
    availableToday: true,
    trending: false,
    short_description:
      "Casual Italian dining with wood-fired pizza, pasta, and classic desserts.",
    features: [
      "Wood Fired Pizza",
      "Wine List",
      "Family Friendly",
      "Outdoor Seating",
    ],
    popular_dishes: [
      "Margherita Pizza",
      "Fettuccine Alfredo",
      "Tiramisu",
    ],
    tags: ["Pizza", "Pasta", "Italian"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 37,
    name: "Pizza Napoli",
    category: "Italian",
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4451,
      longitude: 153.0215,
    },
    price_range: {min: 20, max: 40},
    rating: 4.7,
    reviewCount: 347,
    availableToday: true,
    trending: true,
    short_description:
      "Neapolitan-style pizza with blistered crusts, fresh mozzarella, and simple toppings.",
    features: [
      "Wood Fired Pizza",
      "Wine List",
      "Outdoor Seating",
      "Casual Dining",
    ],
    popular_dishes: [
      "Margherita Pizza",
      "Diavola Pizza",
      "Garlic Bread",
    ],
    tags: ["Pizza", "Italian", "Popular"],
    time_opening: [
      "11:30",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 38,
    name: "Spice of India",
    category: "Indian",
    image:
      "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4721,
      longitude: 153.0119,
    },
    price_range: {min: 20, max: 40},
    rating: 4.6,
    reviewCount: 267,
    availableToday: true,
    trending: false,
    short_description:
      "Aromatic Indian curries, tandoori dishes, and freshly baked naan.",
    features: [
      "Halal",
      "Vegetarian Options",
      "Takeaway",
      "Family Dining",
    ],
    popular_dishes: [
      "Butter Chicken",
      "Lamb Rogan Josh",
      "Garlic Naan",
    ],
    tags: ["Curry", "Indian", "Spicy"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },

  {
    id: 39,
    name: "The Butcher's Block",
    category: "Steakhouse",
    image:
      "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4504,
      longitude: 153.0411,
    },
    price_range: {min: 40, max: 120},
    rating: 4.6,
    reviewCount: 381,
    availableToday: true,
    trending: false,
    short_description:
      "A relaxed steakhouse serving premium cuts, hearty sides, and Australian wines.",
    features: [
      "Wine List",
      "Fine Dining",
      "Private Dining",
      "Large Groups",
    ],
    popular_dishes: [
      "Wagyu Ribeye",
      "Porterhouse Steak",
      "Truffle Fries",
    ],
    tags: ["Steak", "Fine Dining", "Wagyu"],
    time_opening: [
      "11:30",
      "12:00",
      "13:00",
      "14:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 40,
    name: "Golden Dragon",
    category: "Chinese",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4927,
      longitude: 153.0028,
    },
    price_range: {min: 20, max: 60},
    rating: 4.5,
    reviewCount: 312,
    availableToday: true,
    trending: false,
    short_description:
      "Traditional Chinese dining with dumplings, noodles, seafood, and family-style plates.",
    features: [
      "Yum Cha",
      "Takeaway",
      "Family Style",
      "Large Groups",
    ],
    popular_dishes: [
      "Xiao Long Bao",
      "Peking Duck",
      "Kung Pao Chicken",
    ],
    tags: ["Chinese", "Dumplings", "Yum Cha"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },

  {
    id: 41,
    name: "Paella & Co",
    category: "Spanish",
    image:
      "https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4575,
      longitude: 153.0355,
    },
    price_range: { min: 35, max: 80 },
    rating: 4.6,
    reviewCount: 356,
    availableToday: true,
    trending: true,
    short_description:
      "Wood-fired paella pans and Spanish share plates in the heart of Fortitude Valley.",
    features: [
      "Share Plates",
      "Wine List",
      "Outdoor Seating",
      "Group Friendly",
    ],
    popular_dishes: [
      "Seafood Paella",
      "Patatas Bravas",
      "Churros",
    ],
    tags: ["Trending", "Spanish", "Groups"],
    time_opening: [
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 42,
    name: "Mussel & Pan",
    category: "Seafood",
    image:
      "https://images.unsplash.com/photo-1515443961218-a51367888e4b?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.477,
      longitude: 153.036,
    },
    price_range: { min: 40, max: 95 },
    rating: 4.5,
    reviewCount: 241,
    availableToday: true,
    trending: false,
    short_description:
      "Steaming pans of mussels, prawns and clams with cliffside views at Kangaroo Point.",
    features: [
      "City Views",
      "Seafood Bar",
      "Outdoor Seating",
      "Cocktail Bar",
    ],
    popular_dishes: [
      "Chilli Mussels",
      "Garlic Prawns",
      "Clam Linguine",
    ],
    tags: ["Seafood", "Views", "Date Night"],
    time_opening: [
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 43,
    name: "Crumb & Crust Bakery",
    category: "Bakery",
    image:
      "https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4598,
      longitude: 152.999,
    },
    price_range: { min: 8, max: 25 },
    rating: 4.7,
    reviewCount: 512,
    availableToday: true,
    trending: true,
    short_description:
      "Sourdough, pastries and filled baguettes baked fresh every morning in Paddington.",
    features: [
      "Takeaway",
      "Fresh Baked Daily",
      "Coffee",
      "Outdoor Seating",
    ],
    popular_dishes: [
      "Almond Croissant",
      "Sourdough Loaf",
      "Ham & Cheese Baguette",
    ],
    tags: ["Trending", "Bakery", "Breakfast"],
    time_opening: [
      "06:00",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
    ],
  },
  {
    id: 44,
    name: "Sweet Spot Donuts",
    category: "Dessert",
    image:
      "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4816,
      longitude: 153.0094,
    },
    price_range: { min: 6, max: 18 },
    rating: 4.4,
    reviewCount: 389,
    availableToday: true,
    trending: false,
    short_description:
      "Hand-glazed donuts with rotating weekly flavours in West End.",
    features: [
      "Takeaway",
      "Kid Friendly",
      "Vegan Options",
      "Coffee",
    ],
    popular_dishes: [
      "Sprinkle Glazed",
      "Salted Caramel Donut",
      "Boston Cream",
    ],
    tags: ["Dessert", "Sweet Treats", "Family"],
    time_opening: [
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
    ],
  },
  {
    id: 45,
    name: "Gelato Lane",
    category: "Dessert",
    image:
      "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4679,
      longitude: 153.0497,
    },
    price_range: { min: 6, max: 16 },
    rating: 4.6,
    reviewCount: 274,
    availableToday: true,
    trending: false,
    short_description:
      "Small-batch Italian gelato and sorbet churned daily in New Farm.",
    features: [
      "Takeaway",
      "Late Night",
      "Vegan Options",
      "Kid Friendly",
    ],
    popular_dishes: [
      "Pistachio Gelato",
      "Mango Sorbet",
      "Affogato",
    ],
    tags: ["Dessert", "Late Night", "Italian"],
    time_opening: [
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 46,
    name: "Latte Lab",
    category: "Cafe",
    image:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.46,
      longitude: 153.023,
    },
    price_range: { min: 8, max: 22 },
    rating: 4.7,
    reviewCount: 601,
    availableToday: true,
    trending: true,
    short_description:
      "Specialty single-origin coffee and light breakfasts in Spring Hill.",
    features: [
      "Specialty Coffee",
      "Wi-Fi",
      "Takeaway",
      "Outdoor Seating",
    ],
    popular_dishes: [
      "Flat White",
      "Smashed Avocado",
      "Banana Bread",
    ],
    tags: ["Trending", "Coffee", "Work Friendly"],
    time_opening: [
      "06:00",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
    ],
  },
  {
    id: 47,
    name: "Bibimbap Bar",
    category: "Korean",
    image:
      "https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.488,
      longitude: 153.036,
    },
    price_range: { min: 18, max: 40 },
    rating: 4.5,
    reviewCount: 318,
    availableToday: true,
    trending: false,
    short_description:
      "Sizzling stone-pot bibimbap and Korean banchan in Woolloongabba.",
    features: [
      "Casual Dining",
      "Takeaway",
      "Group Friendly",
      "Vegan Options",
    ],
    popular_dishes: [
      "Dolsot Bibimbap",
      "Kimchi Pancake",
      "Bulgogi Beef",
    ],
    tags: ["Korean", "Casual", "Healthy"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },
  {
    id: 48,
    name: "Dhaba Biryani House",
    category: "Indian",
    image:
      "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.438,
      longitude: 153.064,
    },
    price_range: { min: 20, max: 45 },
    rating: 4.6,
    reviewCount: 433,
    availableToday: true,
    trending: false,
    short_description:
      "Slow-cooked dum biryani and tandoor classics in Hamilton.",
    features: [
      "Family Friendly",
      "Takeaway",
      "Vegetarian Options",
      "Group Friendly",
    ],
    popular_dishes: [
      "Chicken Dum Biryani",
      "Butter Naan",
      "Mango Lassi",
    ],
    tags: ["Indian", "Spicy", "Family"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 49,
    name: "Rice Paper Co",
    category: "Vietnamese",
    image:
      "https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.448,
      longitude: 153.013,
    },
    price_range: { min: 15, max: 35 },
    rating: 4.5,
    reviewCount: 287,
    availableToday: true,
    trending: false,
    short_description:
      "Fresh rice paper rolls, vermicelli bowls and Vietnamese coffee in Kelvin Grove.",
    features: [
      "Healthy Options",
      "Takeaway",
      "Gluten Free Options",
      "Casual Dining",
    ],
    popular_dishes: [
      "Prawn Rice Paper Rolls",
      "Lemongrass Chicken Bowl",
      "Vietnamese Iced Coffee",
    ],
    tags: ["Vietnamese", "Healthy", "Lunch"],
    time_opening: [
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
  },
  {
    id: 50,
    name: "Tom Yum Terrace",
    category: "Thai",
    image:
      "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.489,
      longitude: 153.015,
    },
    price_range: { min: 20, max: 48 },
    rating: 4.4,
    reviewCount: 265,
    availableToday: true,
    trending: false,
    short_description:
      "Aromatic Thai soups and curries on a leafy Highgate Hill terrace.",
    features: [
      "Outdoor Seating",
      "Spicy Options",
      "BYO",
      "Group Friendly",
    ],
    popular_dishes: [
      "Tom Yum Goong",
      "Green Curry",
      "Pad See Ew",
    ],
    tags: ["Thai", "Spicy", "BYO"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 51,
    name: "Tonkotsu Alley",
    category: "Japanese",
    image:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.456,
      longitude: 153.047,
    },
    price_range: { min: 18, max: 35 },
    rating: 4.7,
    reviewCount: 548,
    availableToday: true,
    trending: true,
    short_description:
      "Rich 18-hour pork broth ramen and gyoza in Teneriffe.",
    features: [
      "Late Night",
      "Counter Seating",
      "Takeaway",
      "Casual Dining",
    ],
    popular_dishes: [
      "Tonkotsu Ramen",
      "Spicy Miso Ramen",
      "Pork Gyoza",
    ],
    tags: ["Trending", "Ramen", "Late Night"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },
  {
    id: 52,
    name: "Omakase Room",
    category: "Japanese",
    image:
      "https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.4698,
      longitude: 153.0251,
    },
    price_range: { min: 120, max: 220 },
    rating: 4.9,
    reviewCount: 196,
    availableToday: false,
    trending: true,
    short_description:
      "An intimate 12-seat chef's counter serving seasonal omakase in the CBD.",
    features: [
      "Fine Dining",
      "Chef's Counter",
      "Sake List",
      "Bookings Essential",
    ],
    popular_dishes: [
      "Seasonal Omakase",
      "Otoro Nigiri",
      "Uni Hand Roll",
    ],
    tags: ["Trending", "Fine Dining", "Special Occasion"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 53,
    name: "Stack & Syrup",
    category: "Cafe",
    image:
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.452,
      longitude: 153.059,
    },
    price_range: { min: 15, max: 32 },
    rating: 4.5,
    reviewCount: 377,
    availableToday: true,
    trending: false,
    short_description:
      "Fluffy pancake stacks and all-day brunch by the river in Bulimba.",
    features: [
      "All Day Brunch",
      "Kid Friendly",
      "Outdoor Seating",
      "Specialty Coffee",
    ],
    popular_dishes: [
      "Buttermilk Pancakes",
      "Eggs Benedict",
      "Berry Smoothie Bowl",
    ],
    tags: ["Brunch", "Family", "Sweet Treats"],
    time_opening: [
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
    ],
  },
  {
    id: 54,
    name: "Double Stack Burgers",
    category: "American",
    image:
      "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.445,
      longitude: 153.045,
    },
    price_range: { min: 15, max: 30 },
    rating: 4.6,
    reviewCount: 489,
    availableToday: true,
    trending: true,
    short_description:
      "Smashed double-patty burgers, crinkle fries and thick shakes in Newstead.",
    features: [
      "Takeaway",
      "Late Night",
      "Craft Beer",
      "Casual Dining",
    ],
    popular_dishes: [
      "Double Cheeseburger",
      "Loaded Fries",
      "Salted Caramel Shake",
    ],
    tags: ["Trending", "Burgers", "Casual"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },
  {
    id: 55,
    name: "Forno Rosso",
    category: "Italian",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.456,
      longitude: 153.005,
    },
    price_range: { min: 22, max: 50 },
    rating: 4.6,
    reviewCount: 402,
    availableToday: true,
    trending: false,
    short_description:
      "Neapolitan pizza from a red-brick wood-fired oven in Red Hill.",
    features: [
      "Wood-fired Oven",
      "Wine List",
      "Family Friendly",
      "Takeaway",
    ],
    popular_dishes: [
      "Margherita",
      "Diavola",
      "Tiramisu",
    ],
    tags: ["Italian", "Pizza", "Family"],
    time_opening: [
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 56,
    name: "Green Bowl Kitchen",
    category: "Vegan",
    image:
      "https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.485,
      longitude: 152.989,
    },
    price_range: { min: 16, max: 32 },
    rating: 4.5,
    reviewCount: 233,
    availableToday: true,
    trending: false,
    short_description:
      "Plant-based bowls, salads and cold-pressed juices in Toowong.",
    features: [
      "Vegan",
      "Gluten Free Options",
      "Takeaway",
      "Healthy Options",
    ],
    popular_dishes: [
      "Buddha Bowl",
      "Crispy Tofu Salad",
      "Green Detox Juice",
    ],
    tags: ["Vegan", "Healthy", "Lunch"],
    time_opening: [
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
    ],
  },
  {
    id: 57,
    name: "Harbour Lights",
    category: "Seafood",
    image:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.431,
      longitude: 153.059,
    },
    price_range: { min: 70, max: 150 },
    rating: 4.8,
    reviewCount: 318,
    availableToday: false,
    trending: true,
    short_description:
      "Waterfront fine dining with local catch and sunset views in Ascot.",
    features: [
      "Waterfront",
      "Fine Dining",
      "Wine List",
      "Private Dining",
    ],
    popular_dishes: [
      "Moreton Bay Bugs",
      "Seared Scallops",
      "Whole Baked Snapper",
    ],
    tags: ["Trending", "Waterfront", "Date Night"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },
  {
    id: 58,
    name: "Southern Fried Co",
    category: "American",
    image:
      "https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.496,
      longitude: 153.058,
    },
    price_range: { min: 15, max: 32 },
    rating: 4.3,
    reviewCount: 351,
    availableToday: true,
    trending: false,
    short_description:
      "Buttermilk fried chicken, biscuits and hot sauce in Coorparoo.",
    features: [
      "Takeaway",
      "Casual Dining",
      "Craft Beer",
      "Group Friendly",
    ],
    popular_dishes: [
      "Fried Chicken Bucket",
      "Nashville Hot Tenders",
      "Mac & Cheese",
    ],
    tags: ["American", "Comfort Food", "Casual"],
    time_opening: [
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
  },
  {
    id: 59,
    name: "The Pantry Brunch",
    category: "Cafe",
    image:
      "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.47,
      longitude: 153.0,
    },
    price_range: { min: 14, max: 30 },
    rating: 4.6,
    reviewCount: 298,
    availableToday: true,
    trending: false,
    short_description:
      "Seasonal brunch plates and share tables for weekend catch-ups in Milton.",
    features: [
      "All Day Brunch",
      "Group Friendly",
      "Specialty Coffee",
      "Outdoor Seating",
    ],
    popular_dishes: [
      "Brunch Board",
      "Ricotta Hotcakes",
      "Shakshuka",
    ],
    tags: ["Brunch", "Groups", "Weekend"],
    time_opening: [
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
    ],
  },
  {
    id: 60,
    name: "Ember & Oak Grill",
    category: "Steakhouse",
    image:
      "https://images.unsplash.com/photo-1432139555190-58524dae6a55?auto=format&fit=crop&w=1200&q=80",
    location: {
      latitude: -27.48,
      longitude: 153.02,
    },
    price_range: { min: 55, max: 120 },
    rating: 4.7,
    reviewCount: 367,
    availableToday: true,
    trending: false,
    short_description:
      "Charcoal-grilled cuts and seasonal sides in South Brisbane.",
    features: [
      "Charcoal Grill",
      "Wine List",
      "Private Dining",
      "City Views",
    ],
    popular_dishes: [
      "Charred Pork Cutlet",
      "Wagyu Rump",
      "Truffle Mash",
    ],
    tags: ["Steakhouse", "Date Night", "Grill"],
    time_opening: [
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
    ],
  },
];
